### ISSUE TITLE
How to convert BIO output into open IE (subject, predicate, object) tuples

### ISSUE THREAD

**Issue by griff4692** [gabrielStanovsky/supervised-oie#16]
Hi - I'm using the allennlp implementation and trying to figure out how to properly convert from BIO output into (subject, predicate, object) tuples. 

It is clear when you have ARG0 V ARG1, but less clear with the following:

`[ARG1: England] is [V: separated] [ARG2: from continental Europe] [ARG0: by The Irish Sea] [ARG2: to] the east and the [ARG0: English Channel] [ARG2: to the south]`

I would appreciate some guidance on how to parse this.

**Comment by gabrielStanovsky** [comment]
Hi @griff4692 , 
I think that this is a very interesting example.
This is a predicted annotation, right?

To interpret multiple predictions, see this excerpt from [our paper](https://gabrielstanovsky.github.io/assets/papers/naacl18long/paper.pdf) (end of Section 3):
> multiple extractions per predicate are encoded by assigning the same argument index to all arguments appearing in that position across all of the predicate’s extractions. For example, note that the A0 argument label appears twice for the
apposition in example (b). To reconstruct the extractions from the BIO labels, we produce an extraction for every possible way of choosing one argument for each index.

Since in this example we have 2 `ARG0` arguments and 3 `ARG2` arguments, this gives 6 extractions overall:

1.  `(by the Irish sea; separated; England; from continental Europe)` - slightly non-grammatical?
2. `(English Channel; separated; England;  from cotinental Europe)` - pretty good?
3. `(by the Irish sea; separated; England; to the south)` -- incorrect
4. `(English Channel; separated; England; to the south)` -- pretty good?
5. `(by the Irish sea; separated; England; to)` -- bad 
6. `(English Channel; separated; England;  to)` -- bad

Does that make sense?

I think that the errors here stem from the ellipsis in this sentence (it's a form of [gapping](https://en.wikipedia.org/wiki/Ellipsis_(linguistics)#Gapping), maybe?): 
> England is separated from continental Europe by The Irish Sea to the east and [**separated by**] the English Channel to the south

this phenomenon is actually misrepresented in our encoding scheme that assumes the decoding I've pasted above, which holds for example for appositions:

> [ARG0: Barack Obama], [ARG0: the  US president], was [V: born] [ARG1: in Hawaii]

It may be that these examples require a more elaborate annotation scheme in our training data to be better extracted.
